### ISSUE TITLE
Some keys not able to be modified as designed.

### ISSUE THREAD

**Issue by scottgit** [jlopez/serverless-configuration#1]
I have no idea if there is any desire to update this plugin. But if so, one issue I had was that it could not modify `stepFunctions` since that was not a direct key on the `service` of the `serverless` object. 

**Fix**
I believe the fix for this would be change [this line of code](https://github.com/jlopez/serverless-configuration/blob/master/src/index.js#L11) to reference the deeper configuration input. So change:

```js
const { service } = this.serverless;
```

to 

```js
const service = this.serverless.configurationInput;
```

That gives you the whole object build of the configuration file for the service.

**A Workaround**
For others who are trying to use this plugin, a work around is to build your key object to modify that deeper level. So this:

```yml
  serverless-configuration:
    prod:
      add:
        serverless:  # Add this
          configurationInput:  # Add this
            provider:
```
